### ISSUE TITLE
pc-nrfconnect-rssi not compile !

### ISSUE THREAD

**Issue by GianmarcoMicrotech** [NordicSemiconductor/pc-nrfconnect-rssi#34]
Hello,
I'm using the 'SEGGER Embedded Studio for ARM 3.40'. I tried to compile the 'pc-nrfconnect-rssi-master' project , but I have an error.  The error code is 'No such file or directory'. I installed SEGGER on path :''C:\Program Files\SEGGER" and sdk on path:"C:\nordic_semi\nRF5_SDK_15.0.0_a53641a". 
![image1](https://user-images.githubusercontent.com/40670919/42049620-c9c43a94-7b06-11e8-9175-a3d6d247fa9b.png)
Do you have an suggestion for help me ?

**Comment by bencefr** [comment]
Hi @GianmarcoMicrotech , I have no experience with SES, the project files were created for and built with Keil. The firmwares are prebuilt and the source is provided only for reference, they might not be up to the standards of other official firmware sources, more like a proof-of-concept from a javascript developer :)
Also the uart based firmware was originally written for SDK13 and since it was already built, has not been ported or tested with SDK15.

If you really need that firmware to be built, I suggest to check out the v1.0.5 tag and try from there, since SDK13 has different structure and supporting scripts handle them differently.
